// Mocks generated by Mockito 5.4.0 from annotations
// in meteo_app_barge_antony/test/data/repositories/weather_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:meteo_app_barge_antony/data/models/weather_model.dart' as _i5;
import 'package:meteo_app_barge_antony/data/resources/remote/weather_api.dart'
    as _i4;
import 'package:meteo_app_barge_antony/data/models/city_model.dart' as _i6;
import 'package:meteo_app_barge_antony/foundation/network/network_info.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [NetworkInfo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNetworkInfo extends _i1.Mock implements _i2.NetworkInfo {
  MockNetworkInfo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<bool> get isConnected => (super.noSuchMethod(
        Invocation.getter(#isConnected),
        returnValue: _i3.Future<bool>.value(false),
      ) as _i3.Future<bool>);
}

/// A class which mocks [WeatherAPI].
///
/// See the documentation for Mockito's code generation for more information.
class MockWeatherAPI extends _i1.Mock implements _i4.WeatherAPI {
  MockWeatherAPI() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i5.Weather>? getWeather(
    _i6.City? city,
    DateTime? day,
  ) =>
      (super.noSuchMethod(Invocation.method(
        #getWeather,
        [
          city,
          day,
        ],
      )) as _i3.Future<_i5.Weather>?);
}
